name: Предложить функцию (Русский)
description: Предложить улучшение программы.
title: "[Предложение]: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: "Не указывайте приватные данные аккаунта, ссылки на личные медиа или учётные данные."
  - type: textarea
    id: problem
    attributes:
      label: Какую проблему нужно решить?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Какое поведение вы предлагаете?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Какие альтернативы вы рассматривали?
